/*
 * Che Workspace Telemetry API
 * This is the API of the Che workspace telemetry manager
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: dfestal@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.eclipse.che.incubator.workspace.telemetry.model;

import java.util.Objects;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

/**
 * Activity
 */

public class Activity {

  public String userId;

  public Activity() {
  }

  public Activity(String userId) {
    this.userId = userId;
  }

  /**
   * Identifier of the user that notified activity
   *
   * @return userId
   **/
  @Schema(
      description = "Identifier of the user that notified activity",
      required = true
  )
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Activity activity = (Activity) o;
    return Objects.equals(this.userId, activity.userId);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Activity {\n");

    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
